name: demi-ou-moitie
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pandas
  - pip:
      - allennlp  # proj
      - black
      - flake8
      - folium  # proj
      - isort
      - mypy
      - pdfplumber  # proj
      - pycodestyle
      - pyflakes